sm8250-common: Declare missing Hals
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.oplus.hardware.cameraextension@1.0::ICameraExtensionService/cameraextensionservice
    vendor.oplus.hardware.cammidasservice@1.0::IMIDASService/default